fotocasa:
  args:
    type: "avila-provincia"
    zone: "todas-las-zonas"
  pipelines:
    - hop-docs

pisos.com:
  args:
    zone: "pisos-guadalajara"
  pipelines:
    - hop-docs

solvia:
  args:
    operacion: "COMPRA"
    tipoVivienda: 1
    idProvincia: 5

example:
  args:
    initial_page: 2
  pipelines:
    - stdout
  requirements:
    numpy