name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to build hopcolony docker image
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest pypi version
        id: version
        run: echo "::set-output name=version::$(python setup.py --version)"
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: docker
          file: docker/Dockerfile
          tags: hopcolony/hopcolony:${{ steps.version.outputs.version }}
          build-args: VERSION=${{ steps.version.outputs.version }}